import Head from "next/head";
import * as S from "../src/components/Home/Home.styled";
import SideBar from "../src/components/Home/SideBar";
import TopBar from "../src/components/Home/TopBar";

const Home = () => {
  return (
    <>
      <Head>
        <title>Chatala</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo.ico" />
      </Head>

      <S.HomeContainer>
        <TopBar />
        <S.Wrapper>
          <SideBar />
        </S.Wrapper>
      </S.HomeContainer>
    </>
  );
};

export default Home;
