import Head from "next/head";
import { Container } from "../src/components/Home/Home.styled";
import TopBar from "../src/components/Home/TopBar";

const Home = () => {
  return (
    <>
      <Head>
        <title>Chatala</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo.ico" />
        <script src="https://kit.fontawesome.com/3b2f60ea72.js" crossOrigin="anonymous"></script>
      </Head>

      <Container>
        <TopBar />
      </Container>
    </>
  );
};

export default Home;
